[package]
name = "png_2_gba"
version = "0.1.0"
authors = ["Liam Taylor <liam.tab@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.7"
toml = "0.5.7"
serde = "1.0"
